select GETDATE()

select DATEADD(day,1,getdate())

SELECT DATEPART(DAY, GETDATE())

Select DATEADD(day,1,DATEADD(DAY,-DATEPART(DAY, GETDATE()),GETDATE()))

select DATEADD(DAY,-DATEPART(DAY, GETDATE()),GETDATE())

SELECT DATEADD(MONTH,1,DATEADD(DAY,-DATEPART(DAY, GETDATE()),GETDATE()))